.gitignore, conf/config.json
=> feat: update config info

Makefile, README.md, cmd/app/app.go, internal/orm/message_match.go, internal/orm/migrate/migrate.go, internal/orm/migrate/migrations/00001_message_match.sql, internal/utils/flags.go
=> feat: add db migrate

.github/workflows/docker.yml
=> feat: change docker image name

internal/controller/contract.go, internal/controller/cross_chain.go, internal/logic/slack/slack.go, internal/orm/migrate/migrate.go
=> feat: fix goroutine exit bug

internal/controller/contract.go, internal/logic/cross_chain/cross_chain.go
=> feat: reduce goroutine number

internal/controller/contract.go
bug: the start number have reseted.
=> feat: fix start reset bug

internal/logic/cross_chain/cross_chain.go, internal/utils/version.go
=> fix: wrong eth start and end block number

internal/logic/cross_chain/cross_chain.go, internal/utils/version.go
=> fix: increase eth balance check batch size

internal/logic/cross_chain/cross_chain.go, internal/utils/version.go
=> fix: postgres deadlock error

internal/logic/cross_chain/gateway_cross_chain.go, internal/logic/cross_chain/messenger_cross_chain.go, internal/utils/version.go
=> fix: uncheck eth balance bug

internal/controller/finalize_batch_check.go, internal/logic/message_match/message.go
=> fix: fix prometheus metrics register painc

README.md, internal/config/config.go, internal/controller/contract.go, internal/controller/cross_chain.go, internal/logic/assembler/assembler.go
=> fix: minor typos

internal/logic/message_match/message.go
=> fix: api bug

internal/controller/contract.go, internal/controller/controller.go, internal/controller/finalize_batch_check.go, internal/utils/version.go
to check if the block number haven't checked by chain_monitor
=> feat: intercept request from rollup

internal/logic/message_match/message.go, internal/utils/version.go
fix rollup api check false bug
=> fix: rollup api check false

internal/logic/assembler/transfer_event_validator.go, internal/logic/assembler/withdraw_root_validator.go, internal/logic/cross_chain/gateway_cross_chain.go, internal/logic/cross_chain/messenger_cross_chain.go, internal/logic/slack/alert_message.go, internal/orm/messenger_message_match.go
fix messenger event don't update the l1_cross_chain_status/l2_cross_chain_status
=> fix: messenger cross chain status

internal/logic/message_match/message.go
=> fix: api check

internal/controller/cross_chain.go, internal/logic/cross_chain/gateway_cross_chain.go
=> feat: update cross chain loop

internal/utils/version.go
=> feat: bump version

internal/logic/cross_chain/messenger_cross_chain.go
=> feat: fix eth balance check bug

internal/utils/version.go
=> bump version to v1.1.18

internal/config/config.go, internal/logic/contracts/l1.go, internal/logic/contracts/l2.go, internal/types/erc20_type.go, internal/utils/version.go
=> feat: support puff gateways

internal/types/erc20_string.go, internal/utils/version.go
=> fix: erc20 types string format

.github/workflows/docker.yml
=> ci: support arm64

internal/logic/message_match/message.go, internal/utils/version.go
=> fix: add batch status failure logs

Dockerfile
=> ci: update base image to go-alpine-builder:1.21

Dockerfile
Fixing the network issue on the workflow
=> ci: fix go-proxy

Dockerfile
Add debugging tool to chain monitor image
=> add debugging tool to image
